"""empty message

Revision ID: b9ee7ea0f70d
Revises: 
Create Date: 2024-05-23 11:32:31.388280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ee7ea0f70d'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
    
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('users')
#     # ### end Alembic commands ###
